spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      #password: Shiyao92.08.10
  jpa:
      database: MYSQL
      show-sql: true
      generate-ddl: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          ddl-auto: update
mybatis:
   mapperLocations: classpath:/mapper/*.xml

application:
  wx:
    url:  https://api.weixin.qq.com

jwt:
#  header: Authorization
  token:
    secret: mySecret
#    7天
#    expiration: 604800

#    一天
    expiration: 86400

qiniu:
  accessKey: HKD8ScF3hY9WfLI1HAC_wDSVHVLn01oJc6aqe_hn
  secretKey: FU8bFl_NuzWqD2SJ6Pe9hnhLyJqZI9XX3RWB194C
  bucket: s8-image
  path: pci8dpzqu.bkt.clouddn.com


server:
    port: 8080    #因为我之前启动了Tomcat，不能继续使用8080，这里按你所需的端口设置
    use-forward-headers: true
    tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      port-header: X-Forwarded-Port
      #其它设置是让Tomcat去Http头信息去获取协议信息，而不是从HttpServletRequest
